FROM mcr.microsoft.com/devcontainers/typescript-node:20

# The 'node' user already exists in this image with UID 1000
# Just ensure it has sudo privileges
RUN apt-get update && apt-get install -y sudo \
    && echo node ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/node \
    && chmod 0440 /etc/sudoers.d/node

USER node